### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by YarikTH** [YarikTH/home#2]
Special topic for my plans with github

- [x] Create github project and learn how to use it
- [ ] Come up with some games and tools ideas
- [ ] Start to implement one of my idea
- [ ] Make a habit of learning new tools, frameworks ect with new project on github that should be completly done
- [ ] Make a portfolio from my github projects
